number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €"
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
train_data: 'all_data'
valid_data: 'all_data/en_val'
workers: 6
batch_size: 4 
optim: 'Adam' # default is Adadelta
lr: 0.01
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 34 
imgH: 64
imgW: 600
rgb: True
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
feature_extractor : 'VGG'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False
load_checkpoint: False
max_epochs: 1
accelerator: 'gpu'
devices: 1
stop_early : False